name: Event activity types and filters 1
on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
  workflow_dispatch:
  push:
    branches:
      - main
      - 'qa-*'
      - 'feature/**'
    paths-ignore:
      - '.github/workflows/*'
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          ls -l ${{ github.workspace }}
          pwd
          npm ci
        working-directory: ${{ github.workspace }}/01+Starting+Project
      - name: Test code
        run: |
          npm run test 
        working-directory: ${{ github.workspace }}/01+Starting+Project
      - name: Build code
        run: |
          npm run build
        working-directory: ${{ github.workspace }}/01+Starting+Project
      - name: Deploy project
        run: |
          echo "Deploying..."
        working-directory: ${{ github.workspace }}/01+Starting+Project