name: first challenge
on: 
  - push

jobs:
  execute-challenge:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v4
      - name: setup node 
        uses: actions/setup-node@v4
        with:
          node-version: 18.x
      - name: install dependencies
        run: |
          cd 04+Practice+Project
          npm ci
      - name: run lints
        run: |
          cd 04+Practice+Project
          npm lint
      - name: run tests
        run: |
          cd 04+Practice+Project
          npm test
      - name: build project
        run: |
          cd 04+Practice+Project
          npm run build
      - name: deploy project
        run: |
          cd 04+Practice+Project
          echo "deploying..." 