name: npm action
on: push
jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v4
      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: install dependencies
        run: |
          ls -lrth
          npm ci
      - name: run tests
        run: npm test 